### ISSUE TITLE
Cannot send transaction: Unhandled Exception: RPCError: got code -32000 with msg "invalid sender".

### ISSUE THREAD

**Issue by Hathoriel** [xclud/web3dart#80] opened 2022-12-15 20:06 UTC
Hi, I cannot send a transaction, it returns me "invalid sender" error. I am adding the following screenshot
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/10884869/207956483-0c3be7e9-51a3-4e53-bc09-7a947f9a4c4b.png">

**Comment by JaafarRammal** [comment] 2022-12-17 19:27
Having the same issue here!

Executing transactions using EthusJS for the same RPC URL, ABI, and wallet works fine, so unsure what the problem is.

**Comment by JaafarRammal** [comment] 2022-12-17 19:32
@Hathoriel you can pass the following optional parameters to the function and it should work!

```dart
await client.sendTransaction(
      credentials,
      Transaction.callContract(
          contract: contract,
          function: transferFunction,
          parameters: [params]),
      fetchChainIdFromNetworkId: true, chainId: null);
```

**Comment by Hathoriel** [comment] 2022-12-17 19:39
Hi, thanks for info. I will try it. 👍

Dne so 17. 12. 2022 20:32 uživatel Jaafar Rammal ***@***.***>
napsal:

**Comment by Hathoriel** [comment] 2022-12-18 20:32
Hi I finally made it working with this code:
`  sendNativeTransaction(String to, String amount, String walletId, String password) async {
    final client = _getEthClient();
    final credentials = await getPrivateKeyEthKey(password, walletId);
    final toAddress = Web3Dart.EthereumAddress.fromHex(to);
    final amountWei = double.parse(amount) * 1000000000;
    print(BigInt.from(amountWei.toInt()));
    final amountToSend = Web3Dart.EtherAmount.fromUnitAndValue(Web3Dart.EtherUnit.gwei, BigInt.from(amountWei.toInt()));
    final transaction = Web3Dart.Transaction(
      to: toAddress,
      value: amountToSend,
      maxGas: 21000,
      gasPrice: Web3Dart.EtherAmount.inWei(BigInt.from(1500000000)),
    );
    print(transaction.toString());
    final response = await client.sendTransaction(credentials, transaction, fetchChainIdFromNetworkId: true, chainId: null);
    print(response);
    return response;
  }`

Main thing which made it working was this part:

 `fetchChainIdFromNetworkId: true, chainId: null`

Would it make sense to add this inside readme? https://pub.dev/packages/web3dart

**Comment by 4xMafole** [comment] 2022-12-22 19:35
This helped. @Hathoriel can you close this issue since the solution has been addressed and tested above.

**Closed** 2022-12-23 12:55 UTC
