### ISSUE TITLE
Value not in range: 32 on balanceOf

### ISSUE THREAD

**Issue by jvinai** [xclud/web3dart#48] opened 2022-06-16 00:02 UTC
Using the contract.dart example and using my own abi for `balanceOf`, i get this `Value not in range: 32` error.

ABI for `balanceOf`:
```
{
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
  ```

**Comment by BrunoHenrique00** [comment] 2022-06-30 21:09
Had the same issue, make sure you are putting the right RPC URL and contract address.
Also, make sure you are calling the same method name on the client and from your own abi

**Comment by kaumudpa** [comment] 2023-03-03 07:56
Duplicate of https://github.com/xclud/web3dart/issues/46

**Comment by xclud** [comment] 2023-03-03 13:47
Thank you guys. I am closing this one. We'll continue in #46.

**Closed by xclud** 2023-03-03 13:47 UTC
